### ISSUE TITLE
swift2

### ISSUE THREAD

**Issue by kingslay** [nsdictionary/CFRuntime#3]
首先先赞一下作者，请问一下打算什么时候支持swift2.能再支持pod就更好了

**Comment by CharlinFeng** [comment]
等Mac OS正式版本出来，我升级Xcode 7就可以升级为Swift 2.0

**Comment by sdhzwm** [comment]
同问

**Comment by nnianhouss** [comment]
Xcode正式版来了，可以更新支持swift2.0了,支持pod了 
模型需要继承自Relfect基类？为什么不能跟MJExtension样？
